# Generated by Django 6.0.5 on 2026-06-02 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=50)),
                ('jugadores_presentes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='FundraiserCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recaudado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_limite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GymRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_asignacion', models.DateField()),
                ('ejercicios', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('rival', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Programado', max_length=50)),
                ('resultado_club', models.IntegerField(default=0)),
                ('resultado_rival', models.IntegerField(default=0)),
                ('titulares', models.JSONField(blank=True, default=list)),
                ('suplentes', models.JSONField(blank=True, default=list)),
                ('estadisticas', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Manager'), ('COACH', 'Profesor'), ('PLAYER', 'Jugador')], max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('categorias', models.JSONField(blank=True, default=list)),
                ('posicion', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.FloatField(default=0.0)),
                ('altura', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('ficha_medica_url', models.URLField(blank=True, null=True)),
                ('ficha_medica_fecha', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
