# Generated by Django 6.0.5 on 2026-06-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
