# Generated by Django 6.0.5 on 2026-06-02 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TercerTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_comida', models.FloatField(default=0)),
                ('costo_bebida', models.FloatField(default=0)),
                ('otros_gastos', models.FloatField(default=0)),
                ('alias_transferencia', models.CharField(max_length=150)),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tercer_tiempo', to='core.match')),
            ],
        ),
    ]
