# Generated by Django 6.0.5 on 2026-06-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tercertiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hora',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='resultadoClub',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='resultadoRival',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
