# Generated by Django 6.0.5 on 2026-06-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_match_hora_match_resultadoclub_match_resultadorival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='jugadores_presentes',
        ),
        migrations.RemoveField(
            model_name='fundraisercampaign',
            name='fecha_limite',
        ),
        migrations.RemoveField(
            model_name='fundraisercampaign',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='fundraisercampaign',
            name='recaudado',
        ),
        migrations.RemoveField(
            model_name='match',
            name='resultado_club',
        ),
        migrations.RemoveField(
            model_name='match',
            name='resultado_rival',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ficha_medica_fecha',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ficha_medica_url',
        ),
        migrations.AddField(
            model_name='attendance',
            name='asistentes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='justificados',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fundraisercampaign',
            name='cantidadPorJugador',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='fundraisercampaign',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundraisercampaign',
            name='fechaDesde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fundraisercampaign',
            name='fechaHasta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fundraisercampaign',
            name='fotoFlyer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fundraisercampaign',
            name='ventasRegistradas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fichaMedicaFecha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fichaMedicaNombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fichaMedicaUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fichajeInstalments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='justificaciones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fundraisercampaign',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gymroutine',
            name='ejercicios',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gymroutine',
            name='fecha_asignacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='estadisticas',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fecha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='lugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='rival',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='suplentes',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='titulares',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='tercertiempo',
            name='alias_transferencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='categorias',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
