# Generated by Django 6.0.5 on 2026-06-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_attendance_jugadores_presentes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymroutine',
            old_name='fecha_asignacion',
            new_name='fechaAsignacion',
        ),
        migrations.AddField(
            model_name='gymroutine',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymroutine',
            name='jugadorId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gymroutine',
            name='posicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gymroutine',
            name='profesorId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gymroutine',
            name='profesorNombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
